"""index extracted fact sources

Revision ID: 6d3aa44d813f
Revises: 860f39311d1c
Create Date: 2026-09-20 10:21:37.343633+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6d3aa44d813f'
down_revision: str | None = '860f39311d1c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_extracted_facts_document', 'extracted_facts', ['source_document_id'], unique=False)
    op.create_index('ix_extracted_facts_message', 'extracted_facts', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_extracted_facts_message', table_name='extracted_facts')
    op.drop_index('ix_extracted_facts_document', table_name='extracted_facts')
    # ### end Alembic commands ###
