"""goods receipt corrections

A posted receipt is a statement about what physically arrived, so it is never
edited or deleted. A correction is a separate row against it, and the stock it
removes leaves through the ledger like any other movement — which is why
``movement_type`` gains ``receipt_correction`` rather than reusing
``adjustment``: the ledger has to keep being able to answer "what did this
supplier actually deliver?" without counting a keying error as a delivery.

Revision ID: 24790e723b6a
Revises: 6d3aa44d813f
Create Date: 2026-09-20 11:27:06.903879+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '24790e723b6a'
down_revision: str | None = '6d3aa44d813f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Alembic's autogenerate never sees a new value on a native enum, so this
    # is written by hand. PostgreSQL 12+ allows ADD VALUE inside a transaction
    # as long as the new value is not *used* in the same one; this migration
    # only declares it, so that holds.
    op.execute(
        "alter type movement_type add value if not exists 'receipt_correction'"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_order_receipt_corrections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_line_id', sa.UUID(), nullable=False),
    sa.Column('accepted_delta', sa.Numeric(precision=18, scale=3), server_default='0', nullable=False),
    sa.Column('rejected_delta', sa.Numeric(precision=18, scale=3), server_default='0', nullable=False),
    # create_type=False: unit_of_measure already exists. Left as autogenerated,
    # create_table would try to CREATE TYPE a second time and fail.
    sa.Column(
        'unit',
        postgresql.ENUM(name='unit_of_measure', create_type=False),
        nullable=False,
    ),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('corrected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('corrected_by_user_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('inventory_movement_id', sa.UUID(), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('accepted_delta + rejected_delta > 0', name=op.f('ck_purchase_order_receipt_corrections_correction_has_quantity')),
    sa.CheckConstraint('accepted_delta >= 0', name=op.f('ck_purchase_order_receipt_corrections_accepted_delta_non_negative')),
    sa.CheckConstraint('length(trim(reason)) > 0', name=op.f('ck_purchase_order_receipt_corrections_correction_has_reason')),
    sa.CheckConstraint('rejected_delta >= 0', name=op.f('ck_purchase_order_receipt_corrections_rejected_delta_non_negative')),
    sa.ForeignKeyConstraint(['corrected_by_user_id'], ['users.id'], name=op.f('fk_purchase_order_receipt_corrections_corrected_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inventory_movement_id'], ['inventory_movements.id'], name=op.f('fk_purchase_order_receipt_corrections_inventory_movement_id_inventory_movements'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_lines.id'], name=op.f('fk_purchase_order_receipt_corrections_purchase_order_line_id_purchase_order_lines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receipt_id'], ['purchase_order_receipts.id'], name=op.f('fk_purchase_order_receipt_corrections_receipt_id_purchase_order_receipts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('fk_purchase_order_receipt_corrections_source_document_id_source_documents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_receipt_corrections')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_purchase_order_receipt_corrections_idempotency_key'))
    )
    op.create_index(op.f('ix_purchase_order_receipt_corrections_created_at'), 'purchase_order_receipt_corrections', ['created_at'], unique=False)
    op.create_index('ix_receipt_corrections_line', 'purchase_order_receipt_corrections', ['purchase_order_line_id'], unique=False)
    op.create_index('ix_receipt_corrections_receipt', 'purchase_order_receipt_corrections', ['receipt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # A value cannot be removed from a PostgreSQL enum, so the type has to be
    # rebuilt. Refuse rather than destroy: if any movement is a correction,
    # downgrading would have to either drop real ledger rows or silently
    # relabel them as ordinary adjustments, and both change what the ledger
    # says happened.
    in_use = op.get_bind().execute(
        sa.text(
            "select count(*) from inventory_movements "
            "where movement_type = 'receipt_correction'"
        )
    ).scalar()
    if in_use:
        raise RuntimeError(
            f"{in_use} inventory movement(s) are receipt corrections. Downgrading "
            "would have to drop or relabel them, which would change what the "
            "ledger says happened. Reverse those corrections first."
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_receipt_corrections_receipt', table_name='purchase_order_receipt_corrections')
    op.drop_index('ix_receipt_corrections_line', table_name='purchase_order_receipt_corrections')
    op.drop_index(op.f('ix_purchase_order_receipt_corrections_created_at'), table_name='purchase_order_receipt_corrections')
    op.drop_table('purchase_order_receipt_corrections')
    # ### end Alembic commands ###

    # Rebuild movement_type without the value. Safe now: the guard above
    # established that nothing uses it.
    op.execute("alter type movement_type rename to movement_type__old")
    op.execute(
        "create type movement_type as enum "
        "('receipt', 'issue', 'return', 'adjustment', 'wastage', "
        "'production_output', 'shipment', 'scrap', 'transfer')"
    )
    op.execute(
        "alter table inventory_movements alter column movement_type "
        "type movement_type using movement_type::text::movement_type"
    )
    op.execute("drop type movement_type__old")
