"""harden approval chain and reservation constraints

Found by an adversarial audit of the schema, not by a failing feature.

* ``approvals`` and ``executions`` hung off ``action_proposals`` with
  ON DELETE CASCADE, and ``action_proposals`` off ``operational_exceptions``
  the same way. Because ``operational_exceptions`` is itself the CASCADE child
  of eight parents, a single ``DELETE FROM production_batches`` removed the
  exception, its evidence, the proposal, the human approval record and the
  execution — leaving audit rows that said somebody approved something with no
  way to recover what. These become RESTRICT: a delete that would destroy an
  approval now fails loudly.

* ``approvals`` had no uniqueness on ``action_proposal_id``, so two operators
  approving at the same moment each got a row and "who authorised this?" had
  two answers.

* ``inventory_reservations`` had no equivalent of the requirement table's
  ``uq_batch_material``, so a re-exploded batch could hold two active
  reservations for one material and halve the stock everyone else could see.

Revision ID: 860f39311d1c
Revises: 6aae03084920
Create Date: 2026-09-20 10:00:35.975635+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '860f39311d1c'
down_revision: str | None = '6aae03084920'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_action_proposals_exception_id_operational_exceptions'), 'action_proposals', type_='foreignkey')
    op.create_foreign_key(op.f('fk_action_proposals_exception_id_operational_exceptions'), 'action_proposals', 'operational_exceptions', ['exception_id'], ['id'], ondelete='RESTRICT')
    op.create_index('uq_approvals_one_decision_per_proposal', 'approvals', ['action_proposal_id'], unique=True)
    op.drop_constraint(op.f('fk_approvals_action_proposal_id_action_proposals'), 'approvals', type_='foreignkey')
    op.create_foreign_key(op.f('fk_approvals_action_proposal_id_action_proposals'), 'approvals', 'action_proposals', ['action_proposal_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('fk_executions_action_proposal_id_action_proposals'), 'executions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_executions_action_proposal_id_action_proposals'), 'executions', 'action_proposals', ['action_proposal_id'], ['id'], ondelete='RESTRICT')
    op.create_index('ix_reservations_batch_status', 'inventory_reservations', ['production_batch_id', 'status'], unique=False)
    op.create_index('uq_active_reservation_per_batch_material', 'inventory_reservations', ['production_batch_id', 'material_id'], unique=True, postgresql_where=sa.text("status = 'active' and production_batch_id is not null"))

    # A released reservation with no released_at still looks live to anything
    # reading timestamps. Stamp the existing ones before the constraint that
    # forbids new ones, so the migration cannot fail on historical rows.
    op.execute(
        "update inventory_reservations set released_at = coalesce(updated_at, now()) "
        "where status = 'released' and released_at is null"
    )
    op.create_check_constraint(
        "reservation_released_has_timestamp",
        "inventory_reservations",
        "status <> 'released' or released_at is not null",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Spelled out rather than passed through op.f(): the naming convention
    # applies a "ck_<table>_" prefix on the way in, so handing it the already
    # prefixed name produces ck_inventory_reservations_ck_inventory_... and the
    # downgrade fails on a constraint that does not exist.
    op.execute(
        "alter table inventory_reservations drop constraint "
        "ck_inventory_reservations_reservation_released_has_timestamp"
    )
    op.drop_index('uq_active_reservation_per_batch_material', table_name='inventory_reservations', postgresql_where=sa.text("status = 'active' and production_batch_id is not null"))
    op.drop_index('ix_reservations_batch_status', table_name='inventory_reservations')
    op.drop_constraint(op.f('fk_executions_action_proposal_id_action_proposals'), 'executions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_executions_action_proposal_id_action_proposals'), 'executions', 'action_proposals', ['action_proposal_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_approvals_action_proposal_id_action_proposals'), 'approvals', type_='foreignkey')
    op.create_foreign_key(op.f('fk_approvals_action_proposal_id_action_proposals'), 'approvals', 'action_proposals', ['action_proposal_id'], ['id'], ondelete='CASCADE')
    op.drop_index('uq_approvals_one_decision_per_proposal', table_name='approvals')
    op.drop_constraint(op.f('fk_action_proposals_exception_id_operational_exceptions'), 'action_proposals', type_='foreignkey')
    op.create_foreign_key(op.f('fk_action_proposals_exception_id_operational_exceptions'), 'action_proposals', 'operational_exceptions', ['exception_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
