"""record how a message was attributed to a supplier

Invariant 7 says what authorises an automatic change must be deterministic —
and the authorising fact has to be something the sender could not simply write
down. ``messages.supplier_id`` was being set from the supplier name a model
read out of the untrusted message *body*, and the authority check then
short-circuited on that field. Signing an email "Regards, Sri Balaji Spinning"
was enough to be treated as Sri Balaji Spinning, and any sender who could
guess a purchase order number — they are not secret — could move its delivery
date.

The link itself is still useful for finding a message later. This column
records how it was made, so only "caller" (a signed-in operator said so) and
"sender_address" (the transport told us) can authorise anything.

Existing rows are left NULL: that is the honest answer for a message whose
attribution basis was never recorded, and NULL is not in the authoritative
set, so nothing historical is silently trusted.

Revision ID: ebc5db85c828
Revises: 57f3be57cca6
Create Date: 2026-09-20 15:06:54.742298+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ebc5db85c828'
down_revision: str | None = '57f3be57cca6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('supplier_attribution', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'supplier_attribution')
    # ### end Alembic commands ###
