"""actor columns survive user deletion

Thirteen columns referenced ``users``. Eleven of them record something a
person *did* — who proposed an action, who executed it, who moved the stock,
who inspected the cloth, who supplied the document — and every one of those
was ON DELETE SET NULL. Deleting an account would have rewritten months of
history into "somebody", which is the half of a record a dispute actually
turns on.

Those become RESTRICT, so a hard delete fails loudly and pushes the operator
towards deactivation (``users.is_active``), which keeps the history intact and
stops the account working immediately.

Two stay SET NULL deliberately: ``operational_exceptions.owner_user_id`` is an
assignment, and unassigning an open exception when somebody leaves is exactly
right; ``business_metric_events.user_id`` is instrumentation, not a business
record.

``operational_exceptions.resolved_by_user_id`` is new. "Who decided this was
dealt with?" was previously only answerable by searching the audit trail

Revision ID: 57f3be57cca6
Revises: 63e764d09683
Create Date: 2026-09-20 12:38:05.095718+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '57f3be57cca6'
down_revision: str | None = '63e764d09683'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_action_proposals_created_by_user_id_users'), 'action_proposals', type_='foreignkey')
    op.create_foreign_key(op.f('fk_action_proposals_created_by_user_id_users'), 'action_proposals', 'users', ['created_by_user_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('fk_audit_events_actor_user_id_users'), 'audit_events', type_='foreignkey')
    op.create_foreign_key(op.f('fk_audit_events_actor_user_id_users'), 'audit_events', 'users', ['actor_user_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('fk_executions_executed_by_user_id_users'), 'executions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_executions_executed_by_user_id_users'), 'executions', 'users', ['executed_by_user_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('fk_inventory_movements_created_by_user_id_users'), 'inventory_movements', type_='foreignkey')
    op.create_foreign_key(op.f('fk_inventory_movements_created_by_user_id_users'), 'inventory_movements', 'users', ['created_by_user_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('fk_investigations_requested_by_user_id_users'), 'investigations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_investigations_requested_by_user_id_users'), 'investigations', 'users', ['requested_by_user_id'], ['id'], ondelete='RESTRICT')
    op.add_column('operational_exceptions', sa.Column('resolved_by_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_operational_exceptions_resolved_by_user_id_users'), 'operational_exceptions', 'users', ['resolved_by_user_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('fk_production_events_created_by_user_id_users'), 'production_events', type_='foreignkey')
    op.create_foreign_key(op.f('fk_production_events_created_by_user_id_users'), 'production_events', 'users', ['created_by_user_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('fk_qc_inspections_inspector_user_id_users'), 'qc_inspections', type_='foreignkey')
    op.create_foreign_key(op.f('fk_qc_inspections_inspector_user_id_users'), 'qc_inspections', 'users', ['inspector_user_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('fk_reconciliation_items_resolved_by_user_id_users'), 'reconciliation_items', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reconciliation_items_resolved_by_user_id_users'), 'reconciliation_items', 'users', ['resolved_by_user_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('fk_source_documents_uploaded_by_user_id_users'), 'source_documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_source_documents_uploaded_by_user_id_users'), 'source_documents', 'users', ['uploaded_by_user_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_source_documents_uploaded_by_user_id_users'), 'source_documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_source_documents_uploaded_by_user_id_users'), 'source_documents', 'users', ['uploaded_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('fk_reconciliation_items_resolved_by_user_id_users'), 'reconciliation_items', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reconciliation_items_resolved_by_user_id_users'), 'reconciliation_items', 'users', ['resolved_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('fk_qc_inspections_inspector_user_id_users'), 'qc_inspections', type_='foreignkey')
    op.create_foreign_key(op.f('fk_qc_inspections_inspector_user_id_users'), 'qc_inspections', 'users', ['inspector_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('fk_production_events_created_by_user_id_users'), 'production_events', type_='foreignkey')
    op.create_foreign_key(op.f('fk_production_events_created_by_user_id_users'), 'production_events', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('fk_operational_exceptions_resolved_by_user_id_users'), 'operational_exceptions', type_='foreignkey')
    op.drop_column('operational_exceptions', 'resolved_by_user_id')
    op.drop_constraint(op.f('fk_investigations_requested_by_user_id_users'), 'investigations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_investigations_requested_by_user_id_users'), 'investigations', 'users', ['requested_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('fk_inventory_movements_created_by_user_id_users'), 'inventory_movements', type_='foreignkey')
    op.create_foreign_key(op.f('fk_inventory_movements_created_by_user_id_users'), 'inventory_movements', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('fk_executions_executed_by_user_id_users'), 'executions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_executions_executed_by_user_id_users'), 'executions', 'users', ['executed_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('fk_audit_events_actor_user_id_users'), 'audit_events', type_='foreignkey')
    op.create_foreign_key(op.f('fk_audit_events_actor_user_id_users'), 'audit_events', 'users', ['actor_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('fk_action_proposals_created_by_user_id_users'), 'action_proposals', type_='foreignkey')
    op.create_foreign_key(op.f('fk_action_proposals_created_by_user_id_users'), 'action_proposals', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
