"""initial schema

Revision ID: 6c95f536f935
Revises: 
Create Date: 2026-09-19 23:38:37.193009+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6c95f536f935'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Native PostgreSQL enum types created by this migration.
ENUM_TYPES: tuple[str, ...] = (
    "action_type",
    "ai_call_status",
    "approval_decision",
    "business_event_type",
    "currency",
    "document_kind",
    "document_status",
    "entity_type",
    "evidence_kind",
    "exception_status",
    "exception_type",
    "execution_mode",
    "execution_status",
    "fabric_finish",
    "fact_status",
    "job_status",
    "lot_status",
    "material_category",
    "measurement_result",
    "message_direction",
    "message_intent",
    "movement_type",
    "production_event_type",
    "production_stage",
    "production_status",
    "proposal_origin",
    "proposal_status",
    "purchase_order_status",
    "qc_measurement_kind",
    "qc_outcome",
    "reconciliation_status",
    "reservation_status",
    "sales_order_status",
    "severity",
    "shipment_status",
    "source_channel",
    "unit_of_measure",
    "user_role",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_call_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workflow', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('status', sa.Enum('success', 'validation_failed', 'provider_error', 'stubbed', name='ai_call_status'), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=120), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.Enum('sales_order', 'sales_order_line', 'purchase_order', 'purchase_order_line', 'supplier', 'customer', 'material', 'fabric_spec', 'inventory_lot', 'production_batch', 'qc_inspection', 'shipment', 'source_document', 'message', 'exception', 'action_proposal', 'user', name='entity_type'), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_call_logs'))
    )
    op.create_index(op.f('ix_ai_call_logs_created_at'), 'ai_call_logs', ['created_at'], unique=False)
    op.create_index('ix_ai_calls_workflow_time', 'ai_call_logs', ['workflow', 'created_at'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.Enum('INR', 'USD', 'EUR', 'GBP', name='currency'), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('priority_tier', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('priority_tier between 1 and 9', name=op.f('ck_customers_priority_tier_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('code', name=op.f('uq_customers_code'))
    )
    op.create_index(op.f('ix_customers_created_at'), 'customers', ['created_at'], unique=False)
    op.create_index('ix_customers_name', 'customers', ['name'], unique=False)
    op.create_table('fabric_specs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('composition', sa.String(length=120), nullable=False),
    sa.Column('construction', sa.String(length=120), nullable=True),
    sa.Column('gsm', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('width_cm', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('colour', sa.String(length=64), nullable=True),
    sa.Column('shade_code', sa.String(length=32), nullable=True),
    sa.Column('finish', sa.Enum('none', 'mercerised', 'peach', 'calendered', 'enzyme_wash', 'water_repellent', 'anti_microbial', name='fabric_finish'), nullable=False),
    sa.Column('sale_unit', sa.Enum('kg', 'g', 't', 'lb', 'm', 'yd', 'cm', 'in', 'pcs', 'roll', 'cone', 'bag', 'carton', 'sqm', 'l', name='unit_of_measure'), nullable=False),
    sa.Column('standard_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.Enum('INR', 'USD', 'EUR', 'GBP', name='currency'), nullable=True),
    sa.Column('standard_lead_time_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('gsm > 0', name=op.f('ck_fabric_specs_gsm_positive')),
    sa.CheckConstraint('standard_cost is null or currency is not null', name=op.f('ck_fabric_specs_cost_requires_currency')),
    sa.CheckConstraint('width_cm > 0', name=op.f('ck_fabric_specs_width_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fabric_specs')),
    sa.UniqueConstraint('code', name=op.f('uq_fabric_specs_code'))
    )
    op.create_index(op.f('ix_fabric_specs_created_at'), 'fabric_specs', ['created_at'], unique=False)
    op.create_index('ix_fabric_specs_name', 'fabric_specs', ['name'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('queue', sa.String(length=48), nullable=False),
    sa.Column('task', sa.String(length=80), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'dead', 'skipped', name='job_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('idempotency_key', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempts >= 0', name=op.f('ck_jobs_attempts_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_jobs_idempotency_key'))
    )
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index('ix_jobs_queue_status_runafter', 'jobs', ['queue', 'status', 'run_after'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.Enum('INR', 'USD', 'EUR', 'GBP', name='currency'), nullable=False),
    sa.Column('default_lead_time_days', sa.Integer(), nullable=False),
    sa.Column('on_time_rate', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('default_lead_time_days >= 0', name=op.f('ck_suppliers_lead_time_non_negative')),
    sa.CheckConstraint('on_time_rate is null or (on_time_rate >= 0 and on_time_rate <= 1)', name=op.f('ck_suppliers_on_time_rate_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers')),
    sa.UniqueConstraint('code', name=op.f('uq_suppliers_code'))
    )
    op.create_index(op.f('ix_suppliers_created_at'), 'suppliers', ['created_at'], unique=False)
    op.create_index('ix_suppliers_name', 'suppliers', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('owner', 'operations', 'procurement', 'production', 'quality', 'viewer', name='user_role'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_table('business_metric_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('document_received', 'document_processed', 'extraction_completed', 'reconciliation_required', 'reconciliation_resolved', 'exception_detected', 'exception_viewed', 'exception_investigated', 'exception_resolved', 'exception_dismissed', 'proposal_created', 'proposal_approved', 'proposal_rejected', 'proposal_draft_edited', 'action_executed', 'simulation_event', name='business_event_type'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entity_type', sa.Enum('sales_order', 'sales_order_line', 'purchase_order', 'purchase_order_line', 'supplier', 'customer', 'material', 'fabric_spec', 'inventory_lot', 'production_batch', 'qc_inspection', 'shipment', 'source_document', 'message', 'exception', 'action_proposal', 'user', name='entity_type'), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('duration_ms is null or duration_ms >= 0', name=op.f('ck_business_metric_events_duration_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_business_metric_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_metric_events'))
    )
    op.create_index(op.f('ix_business_metric_events_occurred_at'), 'business_metric_events', ['occurred_at'], unique=False)
    op.create_index('ix_metric_events_type_time', 'business_metric_events', ['event_type', 'occurred_at'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('yarn', 'greige_fabric', 'processed_fabric', 'dye_chemical', 'trim', 'packaging', name='material_category'), nullable=False),
    sa.Column('base_unit', sa.Enum('kg', 'g', 't', 'lb', 'm', 'yd', 'cm', 'in', 'pcs', 'roll', 'cone', 'bag', 'carton', 'sqm', 'l', name='unit_of_measure'), nullable=False),
    sa.Column('composition', sa.String(length=120), nullable=True),
    sa.Column('yarn_count_text', sa.String(length=32), nullable=True),
    sa.Column('yarn_count_ne', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('colour', sa.String(length=64), nullable=True),
    sa.Column('shade_code', sa.String(length=32), nullable=True),
    sa.Column('standard_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.Enum('INR', 'USD', 'EUR', 'GBP', name='currency'), nullable=True),
    sa.Column('reorder_point', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('default_supplier_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(category = 'yarn') or (yarn_count_text is null and yarn_count_ne is null)", name=op.f('ck_materials_yarn_count_only_for_yarn')),
    sa.CheckConstraint('reorder_point is null or reorder_point >= 0', name=op.f('ck_materials_reorder_point_sign')),
    sa.CheckConstraint('standard_cost is null or currency is not null', name=op.f('ck_materials_cost_requires_currency')),
    sa.ForeignKeyConstraint(['default_supplier_id'], ['suppliers.id'], name=op.f('fk_materials_default_supplier_id_suppliers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materials')),
    sa.UniqueConstraint('code', name=op.f('uq_materials_code'))
    )
    op.create_index('ix_materials_category_active', 'materials', ['category', 'is_active'], unique=False)
    op.create_index(op.f('ix_materials_created_at'), 'materials', ['created_at'], unique=False)
    op.create_index('ix_materials_name', 'materials', ['name'], unique=False)
    op.create_table('sales_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('promised_date', sa.Date(), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'confirmed', 'in_production', 'ready_to_ship', 'partially_shipped', 'shipped', 'delivered', 'closed', 'cancelled', name='sales_order_status'), nullable=False),
    sa.Column('currency', sa.Enum('INR', 'USD', 'EUR', 'GBP', name='currency'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('incoterms', sa.String(length=32), nullable=True),
    sa.Column('customer_reference', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('priority between 1 and 9', name=op.f('ck_sales_orders_priority_range')),
    sa.CheckConstraint('promised_date >= order_date', name=op.f('ck_sales_orders_promised_after_order')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_sales_orders_customer_id_customers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_orders')),
    sa.UniqueConstraint('number', name=op.f('uq_sales_orders_number'))
    )
    op.create_index(op.f('ix_sales_orders_created_at'), 'sales_orders', ['created_at'], unique=False)
    op.create_index('ix_sales_orders_customer', 'sales_orders', ['customer_id'], unique=False)
    op.create_index('ix_sales_orders_status_promised', 'sales_orders', ['status', 'promised_date'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('planned', 'packed', 'dispatched', 'in_transit', 'delivered', 'delayed', 'cancelled', name='shipment_status'), nullable=False),
    sa.Column('carrier', sa.String(length=120), nullable=True),
    sa.Column('tracking_reference', sa.String(length=120), nullable=True),
    sa.Column('dispatch_date', sa.Date(), nullable=True),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status not in ('dispatched','in_transit','delivered') or dispatch_date is not null", name=op.f('ck_shipments_dispatched_requires_date')),
    sa.CheckConstraint('actual_delivery_date is null or dispatch_date is null or actual_delivery_date >= dispatch_date', name=op.f('ck_shipments_delivery_after_dispatch')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_shipments_customer_id_customers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipments')),
    sa.UniqueConstraint('number', name=op.f('uq_shipments_number'))
    )
    op.create_index(op.f('ix_shipments_created_at'), 'shipments', ['created_at'], unique=False)
    op.create_index('ix_shipments_customer', 'shipments', ['customer_id'], unique=False)
    op.create_index('ix_shipments_status_expected', 'shipments', ['status', 'expected_delivery_date'], unique=False)
    op.create_table('source_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=512), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.Enum('upload', 'email', 'whatsapp', 'manual', 'api', 'simulation', name='source_channel'), nullable=False),
    sa.Column('kind', sa.Enum('unknown', 'purchase_order', 'sales_order', 'invoice', 'packing_list', 'delivery_challan', 'qc_report', 'inventory_snapshot', 'supplier_message', 'customer_message', 'production_log', 'other', name='document_kind'), nullable=False),
    sa.Column('status', sa.Enum('received', 'queued', 'processing', 'extracted', 'needs_review', 'applied', 'failed', 'rejected', name='document_status'), nullable=False),
    sa.Column('classification_confidence', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('doc_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duplicate_of_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('byte_size >= 0', name=op.f('ck_source_documents_byte_size_non_negative')),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['source_documents.id'], name=op.f('fk_source_documents_duplicate_of_id_source_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_source_documents_uploaded_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_documents'))
    )
    op.create_index(op.f('ix_source_documents_created_at'), 'source_documents', ['created_at'], unique=False)
    op.create_index('ix_source_documents_sha256', 'source_documents', ['sha256'], unique=False)
    op.create_index('ix_source_documents_status_received', 'source_documents', ['status', 'received_at'], unique=False)
    op.create_table('fabric_spec_components',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fabric_spec_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('quantity_per_unit', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit', sa.Enum('kg', 'g', 't', 'lb', 'm', 'yd', 'cm', 'in', 'pcs', 'roll', 'cone', 'bag', 'carton', 'sqm', 'l', name='unit_of_measure'), nullable=False),
    sa.Column('wastage_pct', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_per_unit > 0', name=op.f('ck_fabric_spec_components_qty_per_unit_positive')),
    sa.CheckConstraint('wastage_pct >= 0 and wastage_pct < 1', name=op.f('ck_fabric_spec_components_wastage_pct_range')),
    sa.ForeignKeyConstraint(['fabric_spec_id'], ['fabric_specs.id'], name=op.f('fk_fabric_spec_components_fabric_spec_id_fabric_specs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_fabric_spec_components_material_id_materials'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fabric_spec_components')),
    sa.UniqueConstraint('fabric_spec_id', 'material_id', name='uq_spec_material')
    )
    op.create_index(op.f('ix_fabric_spec_components_created_at'), 'fabric_spec_components', ['created_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('upload', 'email', 'whatsapp', 'manual', 'api', 'simulation', name='source_channel'), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='message_direction'), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('external_ref', sa.String(length=200), nullable=True),
    sa.Column('thread_ref', sa.String(length=200), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('intent', sa.Enum('unknown', 'supplier_delay', 'supplier_dispatch', 'supplier_quote', 'order_change', 'order_enquiry', 'quality_complaint', 'payment', 'logistics', 'general', name='message_intent'), nullable=False),
    sa.Column('intent_confidence', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duplicate_of_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_messages_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['messages.id'], name=op.f('fk_messages_duplicate_of_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('fk_messages_source_document_id_source_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_messages_supplier_id_suppliers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_content_hash', 'messages', ['content_hash'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index('ix_messages_intent', 'messages', ['intent'], unique=False)
    op.create_index('ix_messages_received', 'messages', ['received_at'], unique=False)
    op.create_index('ix_messages_supplier_received', 'messages', ['supplier_id', 'received_at'], unique=False)
    op.create_table('sales_order_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sales_order_id', sa.UUID(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('fabric_spec_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit', sa.Enum('kg', 'g', 't', 'lb', 'm', 'yd', 'cm', 'in', 'pcs', 'roll', 'cone', 'bag', 'carton', 'sqm', 'l', name='unit_of_measure'), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('shipped_quantity', sa.Numeric(precision=18, scale=3), server_default='0', nullable=False),
    sa.Column('produced_quantity', sa.Numeric(precision=18, scale=3), server_default='0', nullable=False),
    sa.Column('promised_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('produced_quantity >= 0', name=op.f('ck_sales_order_lines_produced_non_negative')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_sales_order_lines_quantity_positive')),
    sa.CheckConstraint('shipped_quantity >= 0', name=op.f('ck_sales_order_lines_shipped_non_negative')),
    sa.CheckConstraint('unit_price is null or unit_price >= 0', name=op.f('ck_sales_order_lines_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['fabric_spec_id'], ['fabric_specs.id'], name=op.f('fk_sales_order_lines_fabric_spec_id_fabric_specs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], name=op.f('fk_sales_order_lines_sales_order_id_sales_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_order_lines')),
    sa.UniqueConstraint('sales_order_id', 'line_no', name='uq_so_line_no')
    )
    op.create_index(op.f('ix_sales_order_lines_created_at'), 'sales_order_lines', ['created_at'], unique=False)
    op.create_index('ix_sales_order_lines_spec', 'sales_order_lines', ['fabric_spec_id'], unique=False)
    op.create_table('extracted_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('fact_type', sa.String(length=80), nullable=False),
    sa.Column('field_path', sa.String(length=120), nullable=True),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('normalized_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('status', sa.Enum('proposed', 'accepted', 'rejected', 'superseded', 'needs_review', name='fact_status'), nullable=False),
    sa.Column('entity_type', sa.Enum('sales_order', 'sales_order_line', 'purchase_order', 'purchase_order_line', 'supplier', 'customer', 'material', 'fabric_spec', 'inventory_lot', 'production_batch', 'qc_inspection', 'shipment', 'source_document', 'message', 'exception', 'action_proposal', 'user', name='entity_type'), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('ai_request_id', sa.String(length=120), nullable=True),
    sa.Column('extractor_version', sa.String(length=32), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(source_document_id is not null) or (message_id is not null)', name=op.f('ck_extracted_facts_fact_has_a_source')),
    sa.CheckConstraint('confidence is null or (confidence >= 0 and confidence <= 1)', name=op.f('ck_extracted_facts_confidence_range')),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_extracted_facts_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('fk_extracted_facts_source_document_id_source_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['extracted_facts.id'], name=op.f('fk_extracted_facts_superseded_by_id_extracted_facts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extracted_facts'))
    )
    op.create_index(op.f('ix_extracted_facts_created_at'), 'extracted_facts', ['created_at'], unique=False)
    op.create_index('ix_extracted_facts_entity', 'extracted_facts', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_extracted_facts_status_type', 'extracted_facts', ['status', 'fact_type'], unique=False)
    op.create_table('production_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('fabric_spec_id', sa.UUID(), nullable=False),
    sa.Column('sales_order_line_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.Enum('knitting', 'weaving', 'dyeing', 'printing', 'finishing', 'cutting', 'packing', name='production_stage'), nullable=False),
    sa.Column('status', sa.Enum('planned', 'scheduled', 'in_progress', 'blocked', 'completed', 'rework', 'rejected', 'cancelled', name='production_status'), nullable=False),
    sa.Column('planned_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit', sa.Enum('kg', 'g', 't', 'lb', 'm', 'yd', 'cm', 'in', 'pcs', 'roll', 'cone', 'bag', 'carton', 'sqm', 'l', name='unit_of_measure'), nullable=False),
    sa.Column('output_quantity', sa.Numeric(precision=18, scale=3), server_default='0', nullable=False),
    sa.Column('wastage_quantity', sa.Numeric(precision=18, scale=3), server_default='0', nullable=False),
    sa.Column('rejected_quantity', sa.Numeric(precision=18, scale=3), server_default='0', nullable=False),
    sa.Column('planned_start', sa.Date(), nullable=False),
    sa.Column('planned_completion', sa.Date(), nullable=False),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_completion', sa.Date(), nullable=True),
    sa.Column('actual_completion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('depends_on_batch_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('rework_of_batch_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status <> 'blocked') or (blocked_reason is not null)", name=op.f('ck_production_batches_blocked_requires_reason')),
    sa.CheckConstraint('output_quantity >= 0', name=op.f('ck_production_batches_output_non_negative')),
    sa.CheckConstraint('planned_completion >= planned_start', name=op.f('ck_production_batches_completion_after_start')),
    sa.CheckConstraint('planned_quantity > 0', name=op.f('ck_production_batches_planned_quantity_positive')),
    sa.CheckConstraint('priority between 1 and 9', name=op.f('ck_production_batches_priority_range')),
    sa.CheckConstraint('rejected_quantity >= 0', name=op.f('ck_production_batches_rejected_non_negative')),
    sa.CheckConstraint('wastage_quantity >= 0', name=op.f('ck_production_batches_wastage_non_negative')),
    sa.ForeignKeyConstraint(['depends_on_batch_id'], ['production_batches.id'], name=op.f('fk_production_batches_depends_on_batch_id_production_batches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fabric_spec_id'], ['fabric_specs.id'], name=op.f('fk_production_batches_fabric_spec_id_fabric_specs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rework_of_batch_id'], ['production_batches.id'], name=op.f('fk_production_batches_rework_of_batch_id_production_batches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sales_order_line_id'], ['sales_order_lines.id'], name=op.f('fk_production_batches_sales_order_line_id_sales_order_lines'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_production_batches')),
    sa.UniqueConstraint('code', name=op.f('uq_production_batches_code'))
    )
    op.create_index(op.f('ix_production_batches_created_at'), 'production_batches', ['created_at'], unique=False)
    op.create_index('ix_production_batches_order_line', 'production_batches', ['sales_order_line_id'], unique=False)
    op.create_index('ix_production_batches_status_completion', 'production_batches', ['status', 'planned_completion'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=False),
    sa.Column('revised_expected_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'sent', 'acknowledged', 'partially_received', 'received', 'closed', 'cancelled', name='purchase_order_status'), nullable=False),
    sa.Column('currency', sa.Enum('INR', 'USD', 'EUR', 'GBP', name='currency'), nullable=False),
    sa.Column('incoterms', sa.String(length=32), nullable=True),
    sa.Column('supplier_reference', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eta_source_message_id', sa.UUID(), nullable=True),
    sa.Column('eta_source_document_id', sa.UUID(), nullable=True),
    sa.Column('eta_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eta_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('expected_date >= order_date', name=op.f('ck_purchase_orders_expected_after_order')),
    sa.ForeignKeyConstraint(['eta_source_document_id'], ['source_documents.id'], name=op.f('fk_purchase_orders_eta_source_document_id_source_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['eta_source_message_id'], ['messages.id'], name=op.f('fk_purchase_orders_eta_source_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_purchase_orders_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_orders')),
    sa.UniqueConstraint('number', name=op.f('uq_purchase_orders_number'))
    )
    op.create_index(op.f('ix_purchase_orders_created_at'), 'purchase_orders', ['created_at'], unique=False)
    op.create_index('ix_purchase_orders_status_expected', 'purchase_orders', ['status', 'expected_date'], unique=False)
    op.create_index('ix_purchase_orders_supplier', 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('production_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('production_batch_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('created', 'scheduled', 'started', 'paused', 'resumed', 'blocked', 'unblocked', 'output_recorded', 'completed', 'rework_started', 'rejected', 'note', name='production_event_type'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('unit', sa.Enum('kg', 'g', 't', 'lb', 'm', 'yd', 'cm', 'in', 'pcs', 'roll', 'cone', 'bag', 'carton', 'sqm', 'l', name='unit_of_measure'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity is null or unit is not null', name=op.f('ck_production_events_quantity_requires_unit')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_production_events_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['production_batch_id'], ['production_batches.id'], name=op.f('fk_production_events_production_batch_id_production_batches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_production_events'))
    )
    op.create_index('ix_production_events_batch_time', 'production_events', ['production_batch_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_production_events_created_at'), 'production_events', ['created_at'], unique=False)
    op.create_table('production_material_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('production_batch_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('required_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit', sa.Enum('kg', 'g', 't', 'lb', 'm', 'yd', 'cm', 'in', 'pcs', 'roll', 'cone', 'bag', 'carton', 'sqm', 'l', name='unit_of_measure'), nullable=False),
    sa.Column('issued_quantity', sa.Numeric(precision=18, scale=3), server_default='0', nullable=False),
    sa.Column('required_by', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('issued_quantity >= 0', name=op.f('ck_production_material_requirements_issued_non_negative')),
    sa.CheckConstraint('required_quantity > 0', name=op.f('ck_production_material_requirements_required_quantity_positive')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_production_material_requirements_material_id_materials'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['production_batch_id'], ['production_batches.id'], name=op.f('fk_production_material_requirements_production_batch_id_production_batches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_production_material_requirements')),
    sa.UniqueConstraint('production_batch_id', 'material_id', name='uq_batch_material')
    )
    op.create_index('ix_prod_requirements_material_date', 'production_material_requirements', ['material_id', 'required_by'], unique=False)
    op.create_index(op.f('ix_production_material_requirements_created_at'), 'production_material_requirements', ['created_at'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('ordered_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit', sa.Enum('kg', 'g', 't', 'lb', 'm', 'yd', 'cm', 'in', 'pcs', 'roll', 'cone', 'bag', 'carton', 'sqm', 'l', name='unit_of_measure'), nullable=False),
    sa.Column('received_quantity', sa.Numeric(precision=18, scale=3), server_default='0', nullable=False),
    sa.Column('rejected_quantity', sa.Numeric(precision=18, scale=3), server_default='0', nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ordered_quantity > 0', name=op.f('ck_purchase_order_lines_ordered_quantity_positive')),
    sa.CheckConstraint('received_quantity >= 0', name=op.f('ck_purchase_order_lines_received_non_negative')),
    sa.CheckConstraint('rejected_quantity >= 0', name=op.f('ck_purchase_order_lines_rejected_non_negative')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_purchase_order_lines_material_id_materials'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_purchase_order_lines_purchase_order_id_purchase_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_lines')),
    sa.UniqueConstraint('purchase_order_id', 'line_no', name='uq_po_line_no')
    )
    op.create_index(op.f('ix_purchase_order_lines_created_at'), 'purchase_order_lines', ['created_at'], unique=False)
    op.create_index('ix_purchase_order_lines_material', 'purchase_order_lines', ['material_id'], unique=False)
    op.create_table('reconciliation_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('extracted_fact_id', sa.UUID(), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('open', 'resolved', 'dismissed', name='reconciliation_status'), nullable=False),
    sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['extracted_fact_id'], ['extracted_facts.id'], name=op.f('fk_reconciliation_items_extracted_fact_id_extracted_facts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_reconciliation_items_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], name=op.f('fk_reconciliation_items_resolved_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('fk_reconciliation_items_source_document_id_source_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_items'))
    )
    op.create_index(op.f('ix_reconciliation_items_created_at'), 'reconciliation_items', ['created_at'], unique=False)
    op.create_index('ix_reconciliation_status_created', 'reconciliation_items', ['status', 'created_at'], unique=False)
    op.create_table('inventory_lots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lot_code', sa.String(length=48), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=True),
    sa.Column('fabric_spec_id', sa.UUID(), nullable=True),
    sa.Column('quantity_received', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit', sa.Enum('kg', 'g', 't', 'lb', 'm', 'yd', 'cm', 'in', 'pcs', 'roll', 'cone', 'bag', 'carton', 'sqm', 'l', name='unit_of_measure'), nullable=False),
    sa.Column('status', sa.Enum('available', 'quarantine', 'rejected', 'consumed', 'in_transit', name='lot_status'), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('purchase_order_line_id', sa.UUID(), nullable=True),
    sa.Column('production_batch_id', sa.UUID(), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.Enum('INR', 'USD', 'EUR', 'GBP', name='currency'), nullable=True),
    sa.Column('gsm_actual', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('width_cm_actual', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('shade_code_actual', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(material_id is not null) <> (fabric_spec_id is not null)', name=op.f('ck_inventory_lots_lot_is_material_xor_fabric')),
    sa.CheckConstraint('quantity_on_hand >= 0', name=op.f('ck_inventory_lots_on_hand_non_negative')),
    sa.CheckConstraint('quantity_received >= 0', name=op.f('ck_inventory_lots_received_non_negative')),
    sa.CheckConstraint('unit_cost is null or currency is not null', name=op.f('ck_inventory_lots_cost_requires_currency')),
    sa.ForeignKeyConstraint(['fabric_spec_id'], ['fabric_specs.id'], name=op.f('fk_inventory_lots_fabric_spec_id_fabric_specs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_inventory_lots_material_id_materials'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['production_batch_id'], ['production_batches.id'], name=op.f('fk_inventory_lots_production_batch_id_production_batches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_lines.id'], name=op.f('fk_inventory_lots_purchase_order_line_id_purchase_order_lines'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_inventory_lots_supplier_id_suppliers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_lots')),
    sa.UniqueConstraint('lot_code', name=op.f('uq_inventory_lots_lot_code'))
    )
    op.create_index(op.f('ix_inventory_lots_created_at'), 'inventory_lots', ['created_at'], unique=False)
    op.create_index('ix_inventory_lots_material_status', 'inventory_lots', ['material_id', 'status'], unique=False)
    op.create_index('ix_inventory_lots_spec_status', 'inventory_lots', ['fabric_spec_id', 'status'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.Enum('receipt', 'issue', 'return', 'adjustment', 'wastage', 'production_output', 'shipment', 'scrap', 'transfer', name='movement_type'), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit', sa.Enum('kg', 'g', 't', 'lb', 'm', 'yd', 'cm', 'in', 'pcs', 'roll', 'cone', 'bag', 'carton', 'sqm', 'l', name='unit_of_measure'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reference_type', sa.Enum('sales_order', 'sales_order_line', 'purchase_order', 'purchase_order_line', 'supplier', 'customer', 'material', 'fabric_spec', 'inventory_lot', 'production_batch', 'qc_inspection', 'shipment', 'source_document', 'message', 'exception', 'action_proposal', 'user', name='entity_type'), nullable=True),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_delta <> 0', name=op.f('ck_inventory_movements_delta_non_zero')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_inventory_movements_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lot_id'], ['inventory_lots.id'], name=op.f('fk_inventory_movements_lot_id_inventory_lots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('fk_inventory_movements_source_document_id_source_documents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_movements')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_inventory_movements_idempotency_key'))
    )
    op.create_index(op.f('ix_inventory_movements_created_at'), 'inventory_movements', ['created_at'], unique=False)
    op.create_index('ix_inventory_movements_lot_time', 'inventory_movements', ['lot_id', 'occurred_at'], unique=False)
    op.create_index('ix_inventory_movements_ref', 'inventory_movements', ['reference_type', 'reference_id'], unique=False)
    op.create_table('inventory_reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=True),
    sa.Column('fabric_spec_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit', sa.Enum('kg', 'g', 't', 'lb', 'm', 'yd', 'cm', 'in', 'pcs', 'roll', 'cone', 'bag', 'carton', 'sqm', 'l', name='unit_of_measure'), nullable=False),
    sa.Column('status', sa.Enum('active', 'consumed', 'released', name='reservation_status'), nullable=False),
    sa.Column('required_by', sa.Date(), nullable=True),
    sa.Column('sales_order_line_id', sa.UUID(), nullable=True),
    sa.Column('production_batch_id', sa.UUID(), nullable=True),
    sa.Column('lot_id', sa.UUID(), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(material_id is not null) <> (fabric_spec_id is not null)', name=op.f('ck_inventory_reservations_reservation_is_material_xor_fabric')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_inventory_reservations_reservation_quantity_positive')),
    sa.ForeignKeyConstraint(['fabric_spec_id'], ['fabric_specs.id'], name=op.f('fk_inventory_reservations_fabric_spec_id_fabric_specs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lot_id'], ['inventory_lots.id'], name=op.f('fk_inventory_reservations_lot_id_inventory_lots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_inventory_reservations_material_id_materials'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['production_batch_id'], ['production_batches.id'], name=op.f('fk_inventory_reservations_production_batch_id_production_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_order_line_id'], ['sales_order_lines.id'], name=op.f('fk_inventory_reservations_sales_order_line_id_sales_order_lines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_reservations'))
    )
    op.create_index(op.f('ix_inventory_reservations_created_at'), 'inventory_reservations', ['created_at'], unique=False)
    op.create_index('ix_reservations_material_status', 'inventory_reservations', ['material_id', 'status'], unique=False)
    op.create_index('ix_reservations_spec_status', 'inventory_reservations', ['fabric_spec_id', 'status'], unique=False)
    op.create_table('purchase_order_receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_line_id', sa.UUID(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('rejected_quantity', sa.Numeric(precision=18, scale=3), server_default='0', nullable=False),
    sa.Column('unit', sa.Enum('kg', 'g', 't', 'lb', 'm', 'yd', 'cm', 'in', 'pcs', 'roll', 'cone', 'bag', 'carton', 'sqm', 'l', name='unit_of_measure'), nullable=False),
    sa.Column('inventory_lot_id', sa.UUID(), nullable=True),
    sa.Column('supplier_document_ref', sa.String(length=64), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('accepted_quantity + rejected_quantity > 0', name=op.f('ck_purchase_order_receipts_receipt_has_quantity')),
    sa.CheckConstraint('accepted_quantity >= 0', name=op.f('ck_purchase_order_receipts_accepted_non_negative')),
    sa.CheckConstraint('rejected_quantity >= 0', name=op.f('ck_purchase_order_receipts_rejected_non_negative')),
    sa.ForeignKeyConstraint(['inventory_lot_id'], ['inventory_lots.id'], name=op.f('fk_purchase_order_receipts_inventory_lot_id_inventory_lots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_lines.id'], name=op.f('fk_purchase_order_receipts_purchase_order_line_id_purchase_order_lines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('fk_purchase_order_receipts_source_document_id_source_documents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_receipts'))
    )
    op.create_index('ix_po_receipts_line_time', 'purchase_order_receipts', ['purchase_order_line_id', 'received_at'], unique=False)
    op.create_index(op.f('ix_purchase_order_receipts_created_at'), 'purchase_order_receipts', ['created_at'], unique=False)
    op.create_table('qc_inspections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('production_batch_id', sa.UUID(), nullable=True),
    sa.Column('inventory_lot_id', sa.UUID(), nullable=True),
    sa.Column('inspected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.Enum('pass', 'conditional_pass', 'rework', 'reject', 'pending', name='qc_outcome'), nullable=False),
    sa.Column('inspected_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('accepted_quantity', sa.Numeric(precision=18, scale=3), server_default='0', nullable=False),
    sa.Column('rejected_quantity', sa.Numeric(precision=18, scale=3), server_default='0', nullable=False),
    sa.Column('unit', sa.Enum('kg', 'g', 't', 'lb', 'm', 'yd', 'cm', 'in', 'pcs', 'roll', 'cone', 'bag', 'carton', 'sqm', 'l', name='unit_of_measure'), nullable=False),
    sa.Column('inspector_user_id', sa.UUID(), nullable=True),
    sa.Column('reinspection_of_id', sa.UUID(), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(production_batch_id is not null) or (inventory_lot_id is not null)', name=op.f('ck_qc_inspections_inspection_targets_something')),
    sa.CheckConstraint('accepted_quantity + rejected_quantity <= inspected_quantity', name=op.f('ck_qc_inspections_qc_quantities_balance')),
    sa.CheckConstraint('accepted_quantity >= 0', name=op.f('ck_qc_inspections_accepted_non_negative')),
    sa.CheckConstraint('inspected_quantity > 0', name=op.f('ck_qc_inspections_inspected_quantity_positive')),
    sa.CheckConstraint('rejected_quantity >= 0', name=op.f('ck_qc_inspections_rejected_non_negative')),
    sa.ForeignKeyConstraint(['inspector_user_id'], ['users.id'], name=op.f('fk_qc_inspections_inspector_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inventory_lot_id'], ['inventory_lots.id'], name=op.f('fk_qc_inspections_inventory_lot_id_inventory_lots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['production_batch_id'], ['production_batches.id'], name=op.f('fk_qc_inspections_production_batch_id_production_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reinspection_of_id'], ['qc_inspections.id'], name=op.f('fk_qc_inspections_reinspection_of_id_qc_inspections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('fk_qc_inspections_source_document_id_source_documents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qc_inspections')),
    sa.UniqueConstraint('code', name=op.f('uq_qc_inspections_code'))
    )
    op.create_index('ix_qc_inspections_batch', 'qc_inspections', ['production_batch_id'], unique=False)
    op.create_index(op.f('ix_qc_inspections_created_at'), 'qc_inspections', ['created_at'], unique=False)
    op.create_index('ix_qc_inspections_outcome_time', 'qc_inspections', ['outcome', 'inspected_at'], unique=False)
    op.create_table('shipment_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('sales_order_line_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit', sa.Enum('kg', 'g', 't', 'lb', 'm', 'yd', 'cm', 'in', 'pcs', 'roll', 'cone', 'bag', 'carton', 'sqm', 'l', name='unit_of_measure'), nullable=False),
    sa.Column('inventory_lot_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_shipment_lines_shipment_line_quantity_positive')),
    sa.ForeignKeyConstraint(['inventory_lot_id'], ['inventory_lots.id'], name=op.f('fk_shipment_lines_inventory_lot_id_inventory_lots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sales_order_line_id'], ['sales_order_lines.id'], name=op.f('fk_shipment_lines_sales_order_line_id_sales_order_lines'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], name=op.f('fk_shipment_lines_shipment_id_shipments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipment_lines'))
    )
    op.create_index(op.f('ix_shipment_lines_created_at'), 'shipment_lines', ['created_at'], unique=False)
    op.create_index('ix_shipment_lines_order_line', 'shipment_lines', ['sales_order_line_id'], unique=False)
    op.create_table('operational_exceptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('exception_type', sa.Enum('ORDER_AT_RISK', 'ORDER_LATE', 'MATERIAL_SHORTAGE', 'PO_LATE', 'SUPPLIER_DELAY', 'PRODUCTION_DELAY', 'QC_FAILURE', 'SHIPMENT_DELAY', 'QUANTITY_MISMATCH', 'INVENTORY_ANOMALY', name='exception_type'), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', name='severity'), nullable=False),
    sa.Column('status', sa.Enum('open', 'investigating', 'action_proposed', 'resolved', 'dismissed', name='exception_status'), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('investigated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_resolved', sa.Boolean(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.Enum('sales_order', 'sales_order_line', 'purchase_order', 'purchase_order_line', 'supplier', 'customer', 'material', 'fabric_spec', 'inventory_lot', 'production_batch', 'qc_inspection', 'shipment', 'source_document', 'message', 'exception', 'action_proposal', 'user', name='entity_type'), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('sales_order_id', sa.UUID(), nullable=True),
    sa.Column('purchase_order_id', sa.UUID(), nullable=True),
    sa.Column('production_batch_id', sa.UUID(), nullable=True),
    sa.Column('material_id', sa.UUID(), nullable=True),
    sa.Column('shipment_id', sa.UUID(), nullable=True),
    sa.Column('qc_inspection_id', sa.UUID(), nullable=True),
    sa.Column('impact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detection_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status <> 'dismissed') or (dismissed_at is not null)", name=op.f('ck_operational_exceptions_dismissed_requires_timestamp')),
    sa.CheckConstraint("(status <> 'resolved') or (resolved_at is not null)", name=op.f('ck_operational_exceptions_resolved_requires_timestamp')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_operational_exceptions_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_operational_exceptions_material_id_materials'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_operational_exceptions_owner_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['production_batch_id'], ['production_batches.id'], name=op.f('fk_operational_exceptions_production_batch_id_production_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_operational_exceptions_purchase_order_id_purchase_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['qc_inspection_id'], ['qc_inspections.id'], name=op.f('fk_operational_exceptions_qc_inspection_id_qc_inspections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], name=op.f('fk_operational_exceptions_sales_order_id_sales_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], name=op.f('fk_operational_exceptions_shipment_id_shipments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_operational_exceptions_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operational_exceptions')),
    sa.UniqueConstraint('code', name=op.f('uq_operational_exceptions_code')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_operational_exceptions_dedupe_key'))
    )
    op.create_index('ix_exceptions_entity', 'operational_exceptions', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_exceptions_priority', 'operational_exceptions', ['priority_score'], unique=False)
    op.create_index('ix_exceptions_status_severity', 'operational_exceptions', ['status', 'severity'], unique=False)
    op.create_index('ix_exceptions_type_status', 'operational_exceptions', ['exception_type', 'status'], unique=False)
    op.create_index(op.f('ix_operational_exceptions_created_at'), 'operational_exceptions', ['created_at'], unique=False)
    op.create_table('qc_measurements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('qc_inspection_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('gsm', 'width_cm', 'shade', 'shrinkage_pct', 'defect_points', 'colour_fastness', 'ph', 'tensile_strength', 'other', name='qc_measurement_kind'), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('observed_value', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('observed_text', sa.String(length=200), nullable=True),
    sa.Column('target_value', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('tolerance_low', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('tolerance_high', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unit_text', sa.String(length=32), nullable=True),
    sa.Column('result', sa.Enum('within_tolerance', 'out_of_tolerance', 'not_assessed', name='measurement_result'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind <> 'other' or label is not null", name=op.f('ck_qc_measurements_other_kind_needs_label')),
    sa.CheckConstraint('observed_value is not null or observed_text is not null', name=op.f('ck_qc_measurements_measurement_has_observation')),
    sa.ForeignKeyConstraint(['qc_inspection_id'], ['qc_inspections.id'], name=op.f('fk_qc_measurements_qc_inspection_id_qc_inspections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qc_measurements'))
    )
    op.create_index(op.f('ix_qc_measurements_created_at'), 'qc_measurements', ['created_at'], unique=False)
    op.create_index('ix_qc_measurements_inspection', 'qc_measurements', ['qc_inspection_id'], unique=False)
    op.create_table('action_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('exception_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.Enum('contact_supplier', 'request_revised_eta', 'expedite_shipment', 'schedule_replacement_batch', 'request_qc_reinspection', 'notify_customer', 'change_production_priority', 'reallocate_inventory', 'raise_purchase_order', 'acknowledge_only', name='action_type'), nullable=False),
    sa.Column('execution_mode', sa.Enum('internal', 'external_draft', name='execution_mode'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'approved', 'rejected', 'executed', 'awaiting_external', 'failed', 'cancelled', 'expired', name='proposal_status'), nullable=False),
    sa.Column('origin', sa.Enum('ai_investigation', 'rule_engine', 'human', name='proposal_origin'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('draft_subject', sa.String(length=300), nullable=True),
    sa.Column('draft_body', sa.Text(), nullable=True),
    sa.Column('draft_original_body', sa.Text(), nullable=True),
    sa.Column('draft_edited', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('ai_request_id', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_action_proposals_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exception_id'], ['operational_exceptions.id'], name=op.f('fk_action_proposals_exception_id_operational_exceptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_proposals')),
    sa.UniqueConstraint('code', name=op.f('uq_action_proposals_code'))
    )
    op.create_index(op.f('ix_action_proposals_created_at'), 'action_proposals', ['created_at'], unique=False)
    op.create_index('ix_proposals_exception', 'action_proposals', ['exception_id'], unique=False)
    op.create_index('ix_proposals_status_created', 'action_proposals', ['status', 'created_at'], unique=False)
    op.create_table('exception_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exception_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('calculation', 'record', 'message', 'document', 'timeline', 'ai_hypothesis', name='evidence_kind'), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entity_type', sa.Enum('sales_order', 'sales_order_line', 'purchase_order', 'purchase_order_line', 'supplier', 'customer', 'material', 'fabric_spec', 'inventory_lot', 'production_batch', 'qc_inspection', 'shipment', 'source_document', 'message', 'exception', 'action_proposal', 'user', name='entity_type'), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['operational_exceptions.id'], name=op.f('fk_exception_evidence_exception_id_operational_exceptions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_exception_evidence_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('fk_exception_evidence_source_document_id_source_documents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exception_evidence'))
    )
    op.create_index('ix_evidence_exception_order', 'exception_evidence', ['exception_id', 'sort_order'], unique=False)
    op.create_index(op.f('ix_exception_evidence_created_at'), 'exception_evidence', ['created_at'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exception_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('ai_request_id', sa.String(length=120), nullable=True),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['operational_exceptions.id'], name=op.f('fk_investigations_exception_id_operational_exceptions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_investigations_requested_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigations'))
    )
    op.create_index(op.f('ix_investigations_created_at'), 'investigations', ['created_at'], unique=False)
    op.create_index('ix_investigations_exception', 'investigations', ['exception_id', 'started_at'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action_proposal_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('approved', 'rejected', name='approval_decision'), nullable=False),
    sa.Column('decided_by_user_id', sa.UUID(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('modified_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_proposal_id'], ['action_proposals.id'], name=op.f('fk_approvals_action_proposal_id_action_proposals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], name=op.f('fk_approvals_decided_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals'))
    )
    op.create_index(op.f('ix_approvals_created_at'), 'approvals', ['created_at'], unique=False)
    op.create_index('ix_approvals_proposal', 'approvals', ['action_proposal_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_label', sa.String(length=120), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.Enum('sales_order', 'sales_order_line', 'purchase_order', 'purchase_order_line', 'supplier', 'customer', 'material', 'fabric_spec', 'inventory_lot', 'production_batch', 'qc_inspection', 'shipment', 'source_document', 'message', 'exception', 'action_proposal', 'user', name='entity_type'), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('exception_id', sa.UUID(), nullable=True),
    sa.Column('action_proposal_id', sa.UUID(), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("actor_type in ('user','system','ai')", name=op.f('ck_audit_events_actor_type_values')),
    sa.ForeignKeyConstraint(['action_proposal_id'], ['action_proposals.id'], name=op.f('fk_audit_events_action_proposal_id_action_proposals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_events_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exception_id'], ['operational_exceptions.id'], name=op.f('fk_audit_events_exception_id_operational_exceptions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('fk_audit_events_source_document_id_source_documents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_action_time', 'audit_events', ['action', 'occurred_at'], unique=False)
    op.create_index('ix_audit_entity_time', 'audit_events', ['entity_type', 'entity_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_events_occurred_at'), 'audit_events', ['occurred_at'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action_proposal_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('internal', 'external_draft', name='execution_mode'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', 'awaiting_external', name='execution_status'), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('executed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status <> 'succeeded') or (completed_at is not null)", name=op.f('ck_executions_succeeded_requires_completion')),
    sa.ForeignKeyConstraint(['action_proposal_id'], ['action_proposals.id'], name=op.f('fk_executions_action_proposal_id_action_proposals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['executed_by_user_id'], ['users.id'], name=op.f('fk_executions_executed_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_executions')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_executions_idempotency_key'))
    )
    op.create_index(op.f('ix_executions_created_at'), 'executions', ['created_at'], unique=False)
    op.create_index('ix_executions_proposal', 'executions', ['action_proposal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_executions_proposal', table_name='executions')
    op.drop_index(op.f('ix_executions_created_at'), table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_audit_events_occurred_at'), table_name='audit_events')
    op.drop_index('ix_audit_entity_time', table_name='audit_events')
    op.drop_index('ix_audit_action_time', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_approvals_proposal', table_name='approvals')
    op.drop_index(op.f('ix_approvals_created_at'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index('ix_investigations_exception', table_name='investigations')
    op.drop_index(op.f('ix_investigations_created_at'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_exception_evidence_created_at'), table_name='exception_evidence')
    op.drop_index('ix_evidence_exception_order', table_name='exception_evidence')
    op.drop_table('exception_evidence')
    op.drop_index('ix_proposals_status_created', table_name='action_proposals')
    op.drop_index('ix_proposals_exception', table_name='action_proposals')
    op.drop_index(op.f('ix_action_proposals_created_at'), table_name='action_proposals')
    op.drop_table('action_proposals')
    op.drop_index('ix_qc_measurements_inspection', table_name='qc_measurements')
    op.drop_index(op.f('ix_qc_measurements_created_at'), table_name='qc_measurements')
    op.drop_table('qc_measurements')
    op.drop_index(op.f('ix_operational_exceptions_created_at'), table_name='operational_exceptions')
    op.drop_index('ix_exceptions_type_status', table_name='operational_exceptions')
    op.drop_index('ix_exceptions_status_severity', table_name='operational_exceptions')
    op.drop_index('ix_exceptions_priority', table_name='operational_exceptions')
    op.drop_index('ix_exceptions_entity', table_name='operational_exceptions')
    op.drop_table('operational_exceptions')
    op.drop_index('ix_shipment_lines_order_line', table_name='shipment_lines')
    op.drop_index(op.f('ix_shipment_lines_created_at'), table_name='shipment_lines')
    op.drop_table('shipment_lines')
    op.drop_index('ix_qc_inspections_outcome_time', table_name='qc_inspections')
    op.drop_index(op.f('ix_qc_inspections_created_at'), table_name='qc_inspections')
    op.drop_index('ix_qc_inspections_batch', table_name='qc_inspections')
    op.drop_table('qc_inspections')
    op.drop_index(op.f('ix_purchase_order_receipts_created_at'), table_name='purchase_order_receipts')
    op.drop_index('ix_po_receipts_line_time', table_name='purchase_order_receipts')
    op.drop_table('purchase_order_receipts')
    op.drop_index('ix_reservations_spec_status', table_name='inventory_reservations')
    op.drop_index('ix_reservations_material_status', table_name='inventory_reservations')
    op.drop_index(op.f('ix_inventory_reservations_created_at'), table_name='inventory_reservations')
    op.drop_table('inventory_reservations')
    op.drop_index('ix_inventory_movements_ref', table_name='inventory_movements')
    op.drop_index('ix_inventory_movements_lot_time', table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_created_at'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index('ix_inventory_lots_spec_status', table_name='inventory_lots')
    op.drop_index('ix_inventory_lots_material_status', table_name='inventory_lots')
    op.drop_index(op.f('ix_inventory_lots_created_at'), table_name='inventory_lots')
    op.drop_table('inventory_lots')
    op.drop_index('ix_reconciliation_status_created', table_name='reconciliation_items')
    op.drop_index(op.f('ix_reconciliation_items_created_at'), table_name='reconciliation_items')
    op.drop_table('reconciliation_items')
    op.drop_index('ix_purchase_order_lines_material', table_name='purchase_order_lines')
    op.drop_index(op.f('ix_purchase_order_lines_created_at'), table_name='purchase_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index(op.f('ix_production_material_requirements_created_at'), table_name='production_material_requirements')
    op.drop_index('ix_prod_requirements_material_date', table_name='production_material_requirements')
    op.drop_table('production_material_requirements')
    op.drop_index(op.f('ix_production_events_created_at'), table_name='production_events')
    op.drop_index('ix_production_events_batch_time', table_name='production_events')
    op.drop_table('production_events')
    op.drop_index('ix_purchase_orders_supplier', table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_status_expected', table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_created_at'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index('ix_production_batches_status_completion', table_name='production_batches')
    op.drop_index('ix_production_batches_order_line', table_name='production_batches')
    op.drop_index(op.f('ix_production_batches_created_at'), table_name='production_batches')
    op.drop_table('production_batches')
    op.drop_index('ix_extracted_facts_status_type', table_name='extracted_facts')
    op.drop_index('ix_extracted_facts_entity', table_name='extracted_facts')
    op.drop_index(op.f('ix_extracted_facts_created_at'), table_name='extracted_facts')
    op.drop_table('extracted_facts')
    op.drop_index('ix_sales_order_lines_spec', table_name='sales_order_lines')
    op.drop_index(op.f('ix_sales_order_lines_created_at'), table_name='sales_order_lines')
    op.drop_table('sales_order_lines')
    op.drop_index('ix_messages_supplier_received', table_name='messages')
    op.drop_index('ix_messages_received', table_name='messages')
    op.drop_index('ix_messages_intent', table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index('ix_messages_content_hash', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_fabric_spec_components_created_at'), table_name='fabric_spec_components')
    op.drop_table('fabric_spec_components')
    op.drop_index('ix_source_documents_status_received', table_name='source_documents')
    op.drop_index('ix_source_documents_sha256', table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_created_at'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index('ix_shipments_status_expected', table_name='shipments')
    op.drop_index('ix_shipments_customer', table_name='shipments')
    op.drop_index(op.f('ix_shipments_created_at'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index('ix_sales_orders_status_promised', table_name='sales_orders')
    op.drop_index('ix_sales_orders_customer', table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_created_at'), table_name='sales_orders')
    op.drop_table('sales_orders')
    op.drop_index('ix_materials_name', table_name='materials')
    op.drop_index(op.f('ix_materials_created_at'), table_name='materials')
    op.drop_index('ix_materials_category_active', table_name='materials')
    op.drop_table('materials')
    op.drop_index('ix_metric_events_type_time', table_name='business_metric_events')
    op.drop_index(op.f('ix_business_metric_events_occurred_at'), table_name='business_metric_events')
    op.drop_table('business_metric_events')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_suppliers_name', table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_created_at'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index('ix_jobs_queue_status_runafter', table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_fabric_specs_name', table_name='fabric_specs')
    op.drop_index(op.f('ix_fabric_specs_created_at'), table_name='fabric_specs')
    op.drop_table('fabric_specs')
    op.drop_index('ix_customers_name', table_name='customers')
    op.drop_index(op.f('ix_customers_created_at'), table_name='customers')
    op.drop_table('customers')
    op.drop_index('ix_ai_calls_workflow_time', table_name='ai_call_logs')
    op.drop_index(op.f('ix_ai_call_logs_created_at'), table_name='ai_call_logs')
    op.drop_table('ai_call_logs')
    # ### end Alembic commands ###

    # Alembic does not drop native PostgreSQL enum types it created, which
    # makes a downgrade/upgrade round trip fail on 'type already exists'.
    for enum_name in ENUM_TYPES:
        op.execute(sa.text(f'DROP TYPE IF EXISTS {enum_name}'))
