"""add receipt idempotency key

Revision ID: 6aae03084920
Revises: 6c95f536f935
Create Date: 2026-09-20 04:32:27.423702+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6aae03084920'
down_revision: str | None = '6c95f536f935'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_receipts', sa.Column('idempotency_key', sa.String(length=128), nullable=True))
    op.create_unique_constraint(op.f('uq_purchase_order_receipts_idempotency_key'), 'purchase_order_receipts', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_purchase_order_receipts_idempotency_key'), 'purchase_order_receipts', type_='unique')
    op.drop_column('purchase_order_receipts', 'idempotency_key')
    # ### end Alembic commands ###
